### ISSUE TITLE
Checklist improvements

### ISSUE THREAD

**Issue by Bas-Imth** [Constructive-Tyranny/renegadex-wine-setup-script#5]
- Improve custom launcher.  
- [ ] - Check for updates.  

- Installation Script
- [x] - Check if required download file already exists.  
- [ ] - Get WINE to stfu and not spam the console.
